/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.war.GUI;

import com.war.model.Build;
import com.war.model.Unit;

/**
 *
 * @author ASUS
 */
public class PanelInfo extends javax.swing.JPanel {

    /**
     * Creates new form PanelInfo
     */
    public PanelInfo(int width, int height) {
        this.setBounds(0,0, width, height);
        initComponents();
        imageLabel.setIcon(null);
        unitLabel.setText("Unit :");
        forceLabel.setText("Force :");
        piLabel.setText("HP : ");
    }

    
    public void updateInfoUnit(Unit selected){
        if(selected!=null){
            int hp=(int)((selected.getHealtPoints()*100)/selected.getLifePoints());
            imageLabel.setIcon(selected.getImage());
            unitLabel.setText("Unit :"+selected.getName());
            forceLabel.setText("Force :"+selected.getForce());
            piLabel.setText("HP : "+selected.getHealtPoints() +"/" +selected.getLifePoints());
            lifeBar.setValue( hp);
            
        }else{
            imageLabel.setIcon(null);
            unitLabel.setText("");
            forceLabel.setText("");
            piLabel.setText("");
            lifeBar.setValue(0 );
        }
        
    }
    public void updateInfoBuild(Build selected){
        if(selected!=null){
            int hp=(int)((selected.getHealtPoints()*100)/selected.getLifePoints());
            imageLabel.setIcon(selected.getImage());
            unitLabel.setText("Build :"+selected.getName());
            forceLabel.setText("Capacity :"+selected.getCapacity());
            piLabel.setText("HP : "+selected.getHealtPoints() +"/" +selected.getLifePoints());
            lifeBar.setValue(hp);
            
        }else{
            imageLabel.setIcon(null);
            unitLabel.setText("");
            forceLabel.setText("");
            piLabel.setText("");
            lifeBar.setValue(0 );
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        forceLabel = new javax.swing.JLabel();
        piLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        lifeBar = new javax.swing.JProgressBar();

        panelInfo.setBackground(new java.awt.Color(204, 204, 255));

        forceLabel.setText("Force :");

        piLabel.setText("HP :");

        unitLabel.setText("Unit :");

        lifeBar.setForeground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                        .addComponent(piLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lifeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(forceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(446, 446, 446))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addComponent(unitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lifeBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(piLabel))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel forceLabel;
    public static javax.swing.JLabel imageLabel;
    private javax.swing.JProgressBar lifeBar;
    private javax.swing.JPanel panelInfo;
    public static javax.swing.JLabel piLabel;
    public static javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables
}
